

import type { Documento, ListagemEliminacao, Solicitacao, Usuario, Transferencia, Caixa, TipoOrigem, Classificacao, ParteDocumento, ParteDetalhe, MidiaDetalhe, ClasseJudicial, ApensoDetalhe } from "@/types";
import { getYear, parseISO, isValid } from 'date-fns';

export const AUDIT_LOG_STORAGE_KEY = 'arquivocentral_audit_logs';

export const initialCaixas: Caixa[] = [
  { id: "CX001", codigoCaixa: "CX-A-001", descricao: "Caixa de processos judiciais antigos", tipo: "JUD", status: "Fechada", predio: "Sede", sala: "Arquivo Central", estante: "1", prateleira: "A", situacao: "Completa", condicao: "Ocupada", documentoIds: ["DOC001", "DOC003"] },
  { id: "CX002", codigoCaixa: "CX-B-015", descricao: "Documentos administrativos SIGA", tipo: "ADM/SIGA", status: "Aberta", predio: "Sede", sala: "Arquivo Central", estante: "2", prateleira: "C", situacao: "Incompleta", condicao: "Ocupada", documentoIds: ["DOC002"] },
  { id: "CX003", codigoCaixa: "PST-X-007", descricao: "Pastas de documentos diversos", tipo: "Pasta", status: "Aberta", predio: "Sede", sala: "Arquivo Corrente", estante: "5", prateleira: "B", situacao: "Completa", condicao: "Vazia" },
];

export const placeholderClassificacoesSimulado: Classificacao[] = [
  { id: "CLA001", codigo: "020.1", descricao: "Processos Judiciais Cíveis", status: "Ativo", prazoGuardaFaseIntermediariaAnos: 15, destinacaoFinal: 'Guarda Permanente' as const, tipoPrazoFaseCorrente: "Anos" as const, prazoGuardaFaseCorrenteAnos: 5, tipoPlanoClassificacao: "Judicial" },
  { id: "CLA002", codigo: "030.5", descricao: "Correspondências Recebidas", status: "Inativo", prazoGuardaFaseIntermediariaAnos: 3, destinacaoFinal: 'Eliminação' as const, tipoPrazoFaseCorrente: "Condição Textual" as const, prazoGuardaFaseCorrenteCondicaoTextual: "Até a próxima atualização", tipoPlanoClassificacao: "Administrativo" },
  { id: "CLA003", codigo: "045.2", descricao: "Relatórios Anuais", status: "Ativo", prazoGuardaFaseIntermediariaAnos: 0, destinacaoFinal: 'Guarda Permanente' as const, tipoPrazoFaseCorrente: "Anos" as const, prazoGuardaFaseCorrenteAnos: 1, tipoPlanoClassificacao: "Administrativo" },
];

export const simulatedListagensData: ListagemEliminacao[] = [
  { 
    id: "LE001", 
    numeroListagem: "LE-2023-001", 
    documentoIds: ["DOC001", "DOC007"], 
    dataPublicacaoEdital: new Date("2023-10-15").toISOString(),
    dataProducaoListagem: new Date("2023-09-30").toISOString(),
    numeroEditalCiencia: "EDITAL-005/2023",
    numeroTermoEliminacao: "TE-2023-001",
    dataProducaoTermoEliminacao: new Date("2023-11-01").toISOString(),
    tipoListagem: 'Processos Judiciais',
    unidadeSetor: '1ª Vara Federal',
    observacoes: 'Eliminação de processos cíveis antigos.'
  },
  { 
    id: "LE002", 
    numeroListagem: "LE-2024-001", 
    documentoIds: ["DOC008"], 
    dataPublicacaoEdital: undefined,
    dataProducaoListagem: new Date("2024-02-10").toISOString(),
    tipoListagem: 'Documentos',
    unidadeSetor: 'Arquivo Central',
    observacoes: 'Listagem para documentos diversos.'
  },
];


export const placeholderDocumentos: Documento[] = [
  { 
    id: "DOC001", 
    status: "Arquivado", 
    orgao: "TRF2", 
    origem: "Tribunal de Justiça - TJ", 
    tipoMeio: "Não digital", 
    generoDocumental: "Textual", 
    categoria: "Processo Judicial", 
    tipoDocumento: "Ação Ordinária", 
    numeroDocumento: "PRC-2023-001", 
    processoOriginario: "0123456-78.2022.4.02.5101",
    numeroAntigo: "PA-2015-XYZ",
    dataAbrangente: "01/2023 - 03/2023",
    descricaoDocumento: "Processo referente à disputa contratual X. Este é um exemplo de descrição um pouco mais longa para testar o comportamento da célula na tabela.",
    partes: [{id: 'p1', nome: 'Empresa Exemplo Ltda', tipoParte: 'Autor', cpfCnpj: '12.345.678/0001-99', usarIniciais: true}],
    documentosRelacionadosIds: "DOC002,DOC003",
    dataArquivamento: new Date("2023-01-15").toISOString(), 
    quantidadeVolumes: 1,
    quantidadeApensos: 0,
    apensos: [],
    totalMidias: 0,
    midias: [],
    digitalizado: "Não", 
    tipoBaixa: "",
    dataBaixa: undefined,
    classificacaoArquivisticaId: "CLA001",
    prazoArquivoCorrenteDisplay: "5 Anos",
    prazoArquivoIntermediarioDisplay: "15 Anos",
    destinacaoFinalDisplay: "Guarda Permanente",
    alteracaoDestinacaoFinal: "Não Alterar", 
    anoEliminacaoPrevisto: "2039",
    necessidadeReclassificacao: "Não", 
    segredoJustica: "Não", 
    grauSigilo: "Ostensivo", 
    codigosCaixa: "CX001", 
    codigoAtoM: "ATOM001",
    observacoesGerais: "Nenhuma observação específica para este documento de exemplo.",
    codigoClassificacaoJudicialId: "CJ001",
    numeroListagemEliminacao: "LE-2023-001",
    numeroDocumentoTransferencia: "",
    dataCadastro: new Date("2023-01-01T10:00:00Z").toISOString(), 
  },
  { 
    id: "DOC002", 
    status: "Emprestado", 
    orgao: "SJRJ", 
    origem: "Secretaria Municipal - SM", 
    tipoMeio: "Digital", 
    generoDocumental: "Audiovisual", 
    categoria: "Documento", 
    tipoDocumento: "Solicitação de Informações", 
    numeroDocumento: "OFC-2023-045", 
    processoOriginario: "",
    numeroAntigo: "",
    dataAbrangente: "20/03/2023",
    descricaoDocumento: "Ofício solicitando informações sobre o projeto Y.",
    partes: [{id: 'p2', nome: 'Maria Santos', tipoParte: 'Requerente', cpfCnpj: '123.456.789-00'}],
    documentosRelacionadosIds: "DOC001",
    dataArquivamento: new Date("2023-03-20").toISOString(), 
    quantidadeVolumes: 1,
    quantidadeApensos: 1,
    apensos: [{id: 'ap-d2-1', numeroApenso: 'AP001', caixaApenso: 'CX002'}],
    totalMidias: 1,
    midias: [{id: "m-d2-1", tipoMidia: 'DVD-R', numeroMidia: 'M001', paginaMidia: '1-10', caixaMidia: 'CX-MIDIA-01'}],
    digitalizado: "Sim", 
    tipoBaixa: "Devolvido ao Arquivo",
    dataBaixa: new Date("2023-04-10").toISOString(),
    classificacaoArquivisticaId: "CLA002", 
    prazoArquivoCorrenteDisplay: "Até a próxima atualização",
    prazoArquivoIntermediarioDisplay: "3 Anos",
    destinacaoFinalDisplay: "Eliminação",
    alteracaoDestinacaoFinal: "Não Alterar",
    anoEliminacaoPrevisto: "2027",
    necessidadeReclassificacao: "Sim",
    segredoJustica: "Não", 
    grauSigilo: "Ostensivo", 
    codigosCaixa: "CX002", 
    codigoAtoM: "ATOM002",
    observacoesGerais: "Prioridade alta.",
    codigoClassificacaoJudicialId: "",
    numeroDocumentoTransferencia: "TRANSF_1717088500000",
    dataCadastro: new Date("2023-02-15T11:00:00Z").toISOString(), 
  },
  { 
    id: "DOC003", 
    status: "Arquivado", 
    orgao: "SJES", 
    origem: "Câmara de Vereadores - CV", 
    tipoMeio: "Híbrido", 
    generoDocumental: "Textual", 
    categoria: "Processo Administrativo", 
    tipoDocumento: "Comunicação Interna", 
    numeroDocumento: "MEM-2022-112", 
    processoOriginario: "",
    numeroAntigo: "CI-2022-050",
    dataAbrangente: "05/11/2022",
    descricaoDocumento: "Memorando sobre nova política interna.",
    partes: [{id: 'p3', nome: 'João da Silva', tipoParte: 'Interessado'}],
    documentosRelacionadosIds: "",
    dataArquivamento: new Date("2022-11-05").toISOString(), 
    quantidadeVolumes: 2,
    quantidadeApensos: 0,
    apensos: [],
    totalMidias: 2,
    midias: [
      {id: "m-d3-1", tipoMidia: "Pen Drive", numeroMidia: "M002", paginaMidia: "N/A", caixaMidia: "CX-MIDIA-02"},
      {id: "m-d3-2", tipoMidia: "Pen Drive", numeroMidia: "M003", paginaMidia: "N/A", caixaMidia: "CX-MIDIA-02"},
    ],
    digitalizado: "Sim", 
    tipoBaixa: "",
    dataBaixa: undefined,
    classificacaoArquivisticaId: "CLA003", 
    prazoArquivoCorrenteDisplay: "1 Ano",
    prazoArquivoIntermediarioDisplay: "0 Anos",
    destinacaoFinalDisplay: "Guarda Permanente",
    alteracaoDestinacaoFinal: "Não Alterar", 
    anoEliminacaoPrevisto: "",
    necessidadeReclassificacao: "Não",
    segredoJustica: "Sim", 
    grauSigilo: "Secreto", 
    codigosCaixa: "CX001, CX003", 
    codigoAtoM: "ATOM003",
    observacoesGerais: "Documento de acesso restrito.",
    codigoClassificacaoJudicialId: "",
    numeroDocumentoTransferencia: "",
    dataCadastro: new Date("2022-12-01T09:00:00Z").toISOString(), 
  },
   { 
    id: "DOC004", 
    status: "Eliminado", 
    orgao: "TRF2", 
    origem: "Advocacia Geral - AG", 
    tipoMeio: "Não digital", 
    generoDocumental: "Textual", 
    categoria: "Documento", 
    tipoDocumento: "Requerimento", 
    numeroDocumento: "REQ-2014-001", 
    processoOriginario: "9876543-21.2013.4.02.5101",
    numeroAntigo: "",
    dataAbrangente: "10/06/2014",
    descricaoDocumento: "Requerimento antigo, processo finalizado e eliminado.",
    partes: [{id: 'p4', nome: 'Empresa XYZ', tipoParte: 'Requerente'}],
    documentosRelacionadosIds: "DOC005", 
    dataArquivamento: new Date("2014-06-15").toISOString(), 
    quantidadeVolumes: 1,
    quantidadeApensos: 0,
    apensos: [],
    totalMidias: 0,
    midias: [],
    digitalizado: "Não", 
    tipoBaixa: "Eliminação Concluída",
    dataBaixa: new Date("2018-12-01").toISOString(),
    classificacaoArquivisticaId: "CLA002",
    prazoArquivoCorrenteDisplay: "Até a próxima atualização",
    prazoArquivoIntermediarioDisplay: "3 Anos", 
    destinacaoFinalDisplay: "Eliminação",      
    alteracaoDestinacaoFinal: "Não Alterar", 
    anoEliminacaoPrevisto: "2018",
    necessidadeReclassificacao: "Não", 
    segredoJustica: "Não", 
    grauSigilo: "Ostensivo", 
    codigosCaixa: "CX-TEMP-001", 
    codigoAtoM: "",
    observacoesGerais: "Documento eliminado conforme edital.",
    codigoClassificacaoJudicialId: "",
    numeroDocumentoTransferencia: "",
    dataCadastro: new Date("2014-06-01T10:00:00Z").toISOString(), 
  },
  { 
    id: "DOC005", 
    status: "Aguardando prazo para eliminação", 
    orgao: "SJRJ", 
    origem: "Vara Federal - VF", 
    tipoMeio: "Digital", 
    generoDocumental: "Iconográfico", 
    categoria: "Processo Judicial", 
    tipoDocumento: "Petição", 
    numeroDocumento: "PET-2010-555", 
    processoOriginario: "",
    numeroAntigo: "",
    dataAbrangente: "15/08/2010",
    descricaoDocumento: "Petição inicial do processo, aguardando prazo para eliminação.",
    partes: [{id: 'p5', nome: 'Consumidor Teste', tipoParte: 'Autor'}],
    documentosRelacionadosIds: "",
    dataArquivamento: new Date("2010-08-20").toISOString(), 
    quantidadeVolumes: 0,
    quantidadeApensos: 0,
    apensos: [],
    totalMidias: 1,
    midias: [{id: 'm-d5-1', tipoMidia: 'Outro', numeroMidia: 'ARQ001', paginaMidia: '1-50'}],
    digitalizado: "Sim", 
    tipoBaixa: "",
    dataBaixa: undefined,
    classificacaoArquivisticaId: "CLA001", 
    prazoArquivoCorrenteDisplay: "5 Anos",
    prazoArquivoIntermediarioDisplay: "15 Anos", 
    destinacaoFinalDisplay: "Guarda Permanente", 
    alteracaoDestinacaoFinal: "Não Alterar", 
    anoEliminacaoPrevisto: "2026",
    necessidadeReclassificacao: "Não",
    segredoJustica: "Não", 
    grauSigilo: "Reservado", 
    codigosCaixa: "CX-DIG-010", 
    codigoAtoM: "ATOM005",
    observacoesGerais: "Documento sujeito à análise da CPAD.",
    codigoClassificacaoJudicialId: "CJ001",
    numeroDocumentoTransferencia: "",
    dataCadastro: new Date("2010-08-01T14:00:00Z").toISOString(), 
  },
  { 
    id: "DOC007", 
    status: "Arquivado", 
    orgao: "TRF2", 
    origem: "Vara Cível - VC", 
    tipoMeio: "Não digital", 
    generoDocumental: "Textual", 
    categoria: "Processo Judicial", 
    tipoDocumento: "Execução Fiscal", 
    numeroDocumento: "EXEC-2020-789", 
    processoOriginario: "",
    numeroAntigo: "",
    dataAbrangente: "07/2020 - 12/2020",
    descricaoDocumento: "Processo de execução fiscal.",
    partes: [{id: 'p7', nome: 'Fazenda Nacional', tipoParte: 'Exequente'}],
    documentosRelacionadosIds: "",
    dataArquivamento: new Date("2020-12-15").toISOString(), 
    quantidadeVolumes: 1,
    quantidadeApensos: 0,
    apensos: [],
    totalMidias: 0,
    midias: [],
    digitalizado: "Não", 
    classificacaoArquivisticaId: "CLA001",
    prazoArquivoCorrenteDisplay: "5 Anos",
    prazoArquivoIntermediarioDisplay: "15 Anos",
    destinacaoFinalDisplay: "Guarda Permanente",
    alteracaoDestinacaoFinal: "Não Alterar", 
    anoEliminacaoPrevisto: "2036",
    necessidadeReclassificacao: "Não",
    segredoJustica: "Não", 
    grauSigilo: "Ostensivo", 
    codigosCaixa: "CX004", 
    codigoAtoM: "ATOM007",
    observacoesGerais: "",
    codigoClassificacaoJudicialId: "CJ001",
    numeroListagemEliminacao: "LE-2023-001", 
    numeroDocumentoTransferencia: "",
    dataCadastro: new Date("2020-07-01T10:00:00Z").toISOString(), 
  },
  { 
    id: "DOC008", 
    status: "Aguardando prazo para eliminação", 
    orgao: "SJRJ", 
    origem: "Juizado Especial - JE", 
    tipoMeio: "Digital", 
    generoDocumental: "Textual", 
    categoria: "Processo Judicial", 
    tipoDocumento: "Procedimento do Juizado Especial Cível", 
    numeroDocumento: "JEC-2018-123", 
    processoOriginario: "",
    numeroAntigo: "",
    dataAbrangente: "03/2018",
    descricaoDocumento: "Pequenas causas, aguardando eliminação.",
    partes: [{id: 'p8', nome: 'Fulano de Tal', tipoParte: 'Autor'}],
    documentosRelacionadosIds: "",
    dataArquivamento: new Date("2018-03-20").toISOString(), 
    quantidadeVolumes: 0,
    quantidadeApensos: 0,
    apensos: [],
    totalMidias: 0,
    midias: [],
    digitalizado: "Sim", 
    classificacaoArquivisticaId: "CLA001",
    prazoArquivoCorrenteDisplay: "5 Anos",
    prazoArquivoIntermediarioDisplay: "15 Anos", 
    destinacaoFinalDisplay: "Eliminação", 
    alteracaoDestinacaoFinal: "Não Alterar", 
    anoEliminacaoPrevisto: "2034",
    necessidadeReclassificacao: "Não",
    segredoJustica: "Não", 
    grauSigilo: "Ostensivo", 
    codigosCaixa: "CX-DIG-012", 
    codigoAtoM: "ATOM008",
    observacoesGerais: "Documento digitalizado.",
    codigoClassificacaoJudicialId: "CJ001",
    numeroListagemEliminacao: "LE-2024-001", 
    numeroDocumentoTransferencia: "",
    dataCadastro: new Date("2018-03-01T14:00:00Z").toISOString(), 
  },
  {
    id: "DOC060",
    status: "Arquivado",
    categoria: "Processo Judicial",
    tipoDocumento: "Mandado de Segurança",
    numeroDocumento: "MS-2019-0101",
    dataArquivamento: "2019-11-20T03:00:00.000Z",
    classificacaoArquivisticaId: "CLA001",
    codigosCaixa: "CX-J-100",
    descricaoDocumento: "Mandado de segurança impetrado por Teste S.A. contra ato do Diretor.",
    dataAbrangente: "11/2019",
    destinacaoFinalDisplay: "Guarda Permanente",
    alteracaoDestinacaoFinal: "Não Alterar",
    orgao: "TRF2",
    origem: "Vara Federal - VF",
    tipoMeio: "Não digital",
    generoDocumental: "Textual",
    digitalizado: "Não",
    segredoJustica: "Não",
    grauSigilo: "Ostensivo",
    dataCadastro: "2019-11-20T03:00:00.000Z",
    partes: [{ id: "p060", nome: "Teste S.A.", tipoParte: "Impetrante" }],
  },
  {
    id: "DOC061",
    status: "Arquivado",
    categoria: "Processo Administrativo",
    tipoDocumento: "Processo Licitatório",
    numeroDocumento: "PA-LIC-2021-005",
    dataArquivamento: "2021-08-15T03:00:00.000Z",
    classificacaoArquivisticaId: "CLA004",
    codigosCaixa: "CX-A-201",
    descricaoDocumento: "Licitação para aquisição de material de escritório.",
    dataAbrangente: "08/2021",
    destinacaoFinalDisplay: "Eliminação",
    anoEliminacaoPrevisto: "2033",
    alteracaoDestinacaoFinal: "Não Alterar",
    orgao: "SJRJ",
    origem: "Secretaria de Administração",
    tipoMeio: "Híbrido",
    generoDocumental: "Textual",
    digitalizado: "Sim",
    segredoJustica: "Não",
    grauSigilo: "Ostensivo",
    dataCadastro: "2021-08-15T03:00:00.000Z",
  },
  {
    id: "DOC062",
    status: "Arquivado",
    categoria: "Documento",
    tipoDocumento: "Ata de Reunião",
    numeroDocumento: "ATA-DIR-2023-012",
    dataArquivamento: "2023-09-01T03:00:00.000Z",
    classificacaoArquivisticaId: "CLA003",
    codigosCaixa: "CX-A-202",
    descricaoDocumento: "Ata da 12ª Reunião da Diretoria do ano de 2023.",
    dataAbrangente: "01/09/2023",
    destinacaoFinalDisplay: "Guarda Permanente",
    alteracaoDestinacaoFinal: "Não Alterar",
    orgao: "TRF2",
    origem: "Presidência",
    tipoMeio: "Digital",
    generoDocumental: "Textual",
    digitalizado: "Sim",
    segredoJustica: "Não",
    grauSigilo: "Reservado",
    dataCadastro: "2023-09-01T03:00:00.000Z",
  },
  {
    id: "DOC063",
    status: "Arquivado",
    categoria: "Processo Judicial",
    tipoDocumento: "Habeas Corpus",
    numeroDocumento: "HC-2017-0045",
    dataArquivamento: "2017-05-30T03:00:00.000Z",
    classificacaoArquivisticaId: "CLA001",
    codigosCaixa: "CX-J-101",
    descricaoDocumento: "Habeas Corpus em favor de Paciente Teste.",
    dataAbrangente: "05/2017",
    destinacaoFinalDisplay: "Guarda Permanente",
    alteracaoDestinacaoFinal: "Não Alterar",
    orgao: "TRF2",
    origem: "Gabinete do Desembargador Y",
    tipoMeio: "Não digital",
    generoDocumental: "Textual",
    digitalizado: "Não",
    segredoJustica: "Sim",
    grauSigilo: "Secreto",
    dataCadastro: "2017-05-30T03:00:00.000Z",
    partes: [{ id: "p063", nome: "Paciente Teste", tipoParte: "Paciente" }],
  },
  {
    id: "DOC064",
    status: "Arquivado",
    categoria: "Processo Administrativo",
    tipoDocumento: "Sindicância",
    numeroDocumento: "PA-SIND-2020-002",
    dataArquivamento: "2020-12-10T03:00:00.000Z",
    classificacaoArquivisticaId: "CLA004",
    codigosCaixa: "CX-A-203",
    descricaoDocumento: "Processo de sindicância para apuração de fatos.",
    dataAbrangente: "12/2020",
    destinacaoFinalDisplay: "Eliminação",
    anoEliminacaoPrevisto: "2032",
    alteracaoDestinacaoFinal: "Não Alterar",
    orgao: "SJES",
    origem: "Corregedoria",
    tipoMeio: "Não digital",
    generoDocumental: "Textual",
    digitalizado: "Não",
    segredoJustica: "Não",
    grauSigilo: "Reservado",
    dataCadastro: "2020-12-10T03:00:00.000Z",
  },
  {
    id: "DOC065",
    status: "Arquivado",
    categoria: "Processo Judicial",
    tipoDocumento: "Ação de Cobrança",
    numeroDocumento: "AC-2022-8871",
    dataArquivamento: "2022-07-22T03:00:00.000Z",
    classificacaoArquivisticaId: "CLA001",
    codigosCaixa: "CX-J-102",
    descricaoDocumento: "Ação de cobrança movida pela União.",
    dataAbrangente: "07/2022",
    destinacaoFinalDisplay: "Guarda Permanente",
    alteracaoDestinacaoFinal: "Não Alterar",
    orgao: "SJRJ",
    origem: "Vara de Execução Fiscal",
    tipoMeio: "Digital",
    generoDocumental: "Textual",
    digitalizado: "Sim",
    segredoJustica: "Não",
    grauSigilo: "Ostensivo",
    dataCadastro: "2022-07-22T03:00:00.000Z",
    partes: [{ id: "p065", nome: "União Federal", tipoParte: "Autor" }],
  },
  {
    id: "DOC066",
    status: "Arquivado",
    categoria: "Documento",
    tipoDocumento: "Portaria",
    numeroDocumento: "PORT-PRES-2023-105",
    dataArquivamento: "2023-06-15T03:00:00.000Z",
    classificacaoArquivisticaId: "CLA003",
    codigosCaixa: "CX-A-204",
    descricaoDocumento: "Portaria de designação de comissão.",
    dataAbrangente: "15/06/2023",
    destinacaoFinalDisplay: "Guarda Permanente",
    alteracaoDestinacaoFinal: "Não Alterar",
    orgao: "TRF2",
    origem: "Presidência",
    tipoMeio: "Digital",
    generoDocumental: "Textual",
    digitalizado: "Sim",
    segredoJustica: "Não",
    grauSigilo: "Ostensivo",
    dataCadastro: "2023-06-15T03:00:00.000Z",
  },
  {
    id: "DOC067",
    status: "Arquivado",
    categoria: "Processo Administrativo",
    tipoDocumento: "Pedido de Férias",
    numeroDocumento: "PA-FERIAS-2024-987",
    dataArquivamento: "2024-01-20T03:00:00.000Z",
    classificacaoArquivisticaId: "CLA004",
    codigosCaixa: "CX-A-205",
    descricaoDocumento: "Solicitação de férias do servidor Teste.",
    dataAbrangente: "01/2024",
    destinacaoFinalDisplay: "Eliminação",
    anoEliminacaoPrevisto: "2036",
    alteracaoDestinacaoFinal: "Não Alterar",
    orgao: "SJRJ",
    origem: "Secretaria de Gestão de Pessoas",
    tipoMeio: "Digital",
    generoDocumental: "Textual",
    digitalizado: "Sim",
    segredoJustica: "Não",
    grauSigilo: "Ostensivo",
    dataCadastro: "2024-01-20T03:00:00.000Z",
  },
  {
    id: "DOC068",
    status: "Arquivado",
    categoria: "Processo Judicial",
    tipoDocumento: "Inventário",
    numeroDocumento: "INV-2016-0033",
    dataArquivamento: "2016-10-05T03:00:00.000Z",
    classificacaoArquivisticaId: "CLA001",
    codigosCaixa: "CX-J-103",
    descricaoDocumento: "Processo de inventário e partilha de bens.",
    dataAbrangente: "10/2016",
    destinacaoFinalDisplay: "Guarda Permanente",
    alteracaoDestinacaoFinal: "Não Alterar",
    orgao: "SJES",
    origem: "Vara de Família",
    tipoMeio: "Não digital",
    generoDocumental: "Textual",
    digitalizado: "Não",
    segredoJustica: "Sim",
    grauSigilo: "Reservado",
    dataCadastro: "2016-10-05T03:00:00.000Z",
  },
  {
    id: "DOC069",
    status: "Arquivado",
    categoria: "Documento",
    tipoDocumento: "Certidão",
    numeroDocumento: "CERT-2023-4455",
    dataArquivamento: "2023-03-18T03:00:00.000Z",
    classificacaoArquivisticaId: "CLA003",
    codigosCaixa: "CX-A-206",
    descricaoDocumento: "Certidão de tempo de serviço.",
    dataAbrangente: "18/03/2023",
    destinacaoFinalDisplay: "Guarda Permanente",
    alteracaoDestinacaoFinal: "Não Alterar",
    orgao: "SJRJ",
    origem: "Secretaria de Gestão de Pessoas",
    tipoMeio: "Digital",
    generoDocumental: "Textual",
    digitalizado: "Sim",
    segredoJustica: "Não",
    grauSigilo: "Ostensivo",
    dataCadastro: "2023-03-18T03:00:00.000Z",
  },
  {
    id: "DOC070",
    status: "Arquivado",
    categoria: "Processo Administrativo",
    tipoDocumento: "Prestação de Contas",
    numeroDocumento: "PA-CONTAS-2021-088",
    dataArquivamento: "2022-02-14T03:00:00.000Z",
    classificacaoArquivisticaId: "CLA004",
    codigosCaixa: "CX-A-207",
    descricaoDocumento: "Prestação de contas de convênio.",
    dataAbrangente: "2021",
    destinacaoFinalDisplay: "Eliminação",
    anoEliminacaoPrevisto: "2034",
    alteracaoDestinacaoFinal: "Não Alterar",
    orgao: "TRF2",
    origem: "Secretaria de Orçamento e Finanças",
    tipoMeio: "Híbrido",
    generoDocumental: "Textual",
    digitalizado: "Parcialmente",
    segredoJustica: "Não",
    grauSigilo: "Ostensivo",
    dataCadastro: "2022-02-14T03:00:00.000Z",
  },
  {
    id: "DOC071",
    status: "Arquivado",
    categoria: "Processo Judicial",
    tipoDocumento: "Agravo de Instrumento",
    numeroDocumento: "AI-2021-0234",
    dataArquivamento: "2021-11-11T02:00:00.000Z",
    classificacaoArquivisticaId: "CLA001",
    codigosCaixa: "CX-J-104",
    descricaoDocumento: "Agravo contra decisão interlocutória.",
    dataAbrangente: "11/2021",
    destinacaoFinalDisplay: "Guarda Permanente",
    alteracaoDestinacaoFinal: "Não Alterar",
    orgao: "TRF2",
    origem: "Gabinete do Desembargador Z",
    tipoMeio: "Digital",
    generoDocumental: "Textual",
    digitalizado: "Sim",
    segredoJustica: "Não",
    grauSigilo: "Ostensivo",
    dataCadastro: "2021-11-11T02:00:00.000Z",
  },
  {
    id: "DOC072",
    status: "Arquivado",
    categoria: "Documento",
    tipoDocumento: "Relatório de Atividades",
    numeroDocumento: "RELAT-2023-Q3",
    dataArquivamento: "2023-10-10T03:00:00.000Z",
    classificacaoArquivisticaId: "CLA003",
    codigosCaixa: "CX-A-208",
    descricaoDocumento: "Relatório de atividades do terceiro trimestre de 2023.",
    dataAbrangente: "07/2023 - 09/2023",
    destinacaoFinalDisplay: "Guarda Permanente",
    alteracaoDestinacaoFinal: "Não Alterar",
    orgao: "TRF2",
    origem: "Secretaria de Planejamento",
    tipoMeio: "Digital",
    generoDocumental: "Textual",
    digitalizado: "Sim",
    segredoJustica: "Não",
    grauSigilo: "Ostensivo",
    dataCadastro: "2023-10-10T03:00:00.000Z",
  },
  {
    id: "DOC073",
    status: "Arquivado",
    categoria: "Processo Administrativo",
    tipoDocumento: "Autorização de Viagem",
    numeroDocumento: "PA-VIAGEM-2023-112",
    dataArquivamento: "2023-08-25T03:00:00.000Z",
    classificacaoArquivisticaId: "CLA004",
    codigosCaixa: "CX-A-209",
    descricaoDocumento: "Autorização de viagem nacional para servidor.",
    dataAbrangente: "08/2023",
    destinacaoFinalDisplay: "Eliminação",
    anoEliminacaoPrevisto: "2035",
    alteracaoDestinacaoFinal: "Não Alterar",
    orgao: "SJRJ",
    origem: "Diretoria do Foro",
    tipoMeio: "Digital",
    generoDocumental: "Textual",
    digitalizado: "Sim",
    segredoJustica: "Não",
    grauSigilo: "Ostensivo",
    dataCadastro: "2023-08-25T03:00:00.000Z",
  },
  {
    id: "DOC074",
    status: "Arquivado",
    categoria: "Processo Judicial",
    tipoDocumento: "Embargos à Execução",
    numeroDocumento: "EMB-2018-0099",
    dataArquivamento: "2018-09-17T03:00:00.000Z",
    classificacaoArquivisticaId: "CLA001",
    codigosCaixa: "CX-J-105",
    descricaoDocumento: "Embargos à execução fiscal.",
    dataAbrangente: "09/2018",
    destinacaoFinalDisplay: "Guarda Permanente",
    alteracaoDestinacaoFinal: "Não Alterar",
    orgao: "SJES",
    origem: "Vara de Execução Fiscal",
    tipoMeio: "Não digital",
    generoDocumental: "Textual",
    digitalizado: "Não",
    segredoJustica: "Não",
    grauSigilo: "Ostensivo",
    dataCadastro: "2018-09-17T03:00:00.000Z",
  },
  {
    id: "DOC075",
    status: "Arquivado",
    categoria: "Processo Administrativo",
    tipoDocumento: "Termo de Posse",
    numeroDocumento: "TP-2022-0054",
    dataArquivamento: "2022-04-01T03:00:00.000Z",
    classificacaoArquivisticaId: "CLA004",
    codigosCaixa: "CX-A-210",
    descricaoDocumento: "Termo de posse de novo servidor.",
    dataAbrangente: "01/04/2022",
    destinacaoFinalDisplay: "Eliminação",
    anoEliminacaoPrevisto: "2034",
    alteracaoDestinacaoFinal: "Não Alterar",
    orgao: "TRF2",
    origem: "Secretaria de Gestão de Pessoas",
    tipoMeio: "Não digital",
    generoDocumental: "Textual",
    digitalizado: "Não",
    segredoJustica: "Não",
    grauSigilo: "Ostensivo",
    dataCadastro: "2022-04-01T03:00:00.000Z",
  },
  {
    id: "DOC076",
    status: "Arquivado",
    categoria: "Documento",
    tipoDocumento: "Ofício Recebido",
    numeroDocumento: "OF-EXT-2024-0321",
    dataArquivamento: "2024-02-28T03:00:00.000Z",
    classificacaoArquivisticaId: "CLA003",
    codigosCaixa: "CX-A-211",
    descricaoDocumento: "Ofício recebido do Ministério Público Federal.",
    dataAbrangente: "28/02/2024",
    destinacaoFinalDisplay: "Guarda Permanente",
    alteracaoDestinacaoFinal: "Não Alterar",
    orgao: "TRF2",
    origem: "Protocolo Geral",
    tipoMeio: "Digital",
    generoDocumental: "Textual",
    digitalizado: "Sim",
    segredoJustica: "Não",
    grauSigilo: "Ostensivo",
    dataCadastro: "2024-02-28T03:00:00.000Z",
  },
  {
    id: "DOC077",
    status: "Arquivado",
    categoria: "Processo Judicial",
    tipoDocumento: "Ação Civil Pública",
    numeroDocumento: "ACP-2015-0001",
    dataArquivamento: "2015-03-12T03:00:00.000Z",
    classificacaoArquivisticaId: "CLA001",
    codigosCaixa: "CX-J-106",
    descricaoDocumento: "Ação Civil Pública sobre questões ambientais.",
    dataAbrangente: "2015",
    destinacaoFinalDisplay: "Guarda Permanente",
    alteracaoDestinacaoFinal: "Não Alterar",
    orgao: "SJRJ",
    origem: "Vara Federal Ambiental",
    tipoMeio: "Não digital",
    generoDocumental: "Textual",
    digitalizado: "Não",
    segredoJustica: "Não",
    grauSigilo: "Ostensivo",
    dataCadastro: "2015-03-12T03:00:00.000Z",
  },
  {
    id: "DOC078",
    status: "Arquivado",
    categoria: "Processo Administrativo",
    tipoDocumento: "Designação de Comissão",
    numeroDocumento: "PA-COMIS-2023-040",
    dataArquivamento: "2023-11-08T02:00:00.000Z",
    classificacaoArquivisticaId: "CLA004",
    codigosCaixa: "CX-A-212",
    descricaoDocumento: "Designação de comissão de licitação.",
    dataAbrangente: "08/11/2023",
    destinacaoFinalDisplay: "Eliminação",
    anoEliminacaoPrevisto: "2035",
    alteracaoDestinacaoFinal: "Não Alterar",
    orgao: "TRF2",
    origem: "Diretoria Geral",
    tipoMeio: "Digital",
    generoDocumental: "Textual",
    digitalizado: "Sim",
    segredoJustica: "Não",
    grauSigilo: "Ostensivo",
    dataCadastro: "2023-11-08T02:00:00.000Z",
  },
  {
    id: "DOC079",
    status: "Arquivado",
    categoria: "Documento",
    tipoDocumento: "Parecer Técnico",
    numeroDocumento: "PT-INFRA-2022-076",
    dataArquivamento: "2022-10-21T03:00:00.000Z",
    classificacaoArquivisticaId: "CLA003",
    codigosCaixa: "CX-A-213",
    descricaoDocumento: "Parecer técnico sobre a reforma do edifício anexo.",
    dataAbrangente: "10/2022",
    destinacaoFinalDisplay: "Guarda Permanente",
    alteracaoDestinacaoFinal: "Não Alterar",
    orgao: "TRF2",
    origem: "Secretaria de Engenharia",
    tipoMeio: "Não digital",
    generoDocumental: "Textual",
    digitalizado: "Não",
    segredoJustica: "Não",
    grauSigilo: "Ostensivo",
    dataCadastro: "2022-10-21T03:00:00.000Z",
  }
];

export const placeholderSolicitacoesInitial: Solicitacao[] = [
  { id: "SOL001", tipo: "Empréstimo", numeroSolicitacao: "SOL-2024-001", nomeSolicitante: "João Silva", setorSolicitante: "Gab. Des. A", siglaServidor: "JSS", matriculaSolicitante: "12345", ramal: "1234", emailContato: "joao.silva@trf2.jus.br", dataSolicitacao: new Date("2024-03-01").toISOString(), documentoIds: ["DOC001"], status: "Pendente" },
  { id: "SOL002", tipo: "Desarquivamento", numeroSolicitacao: "SOL-2024-002", nomeSolicitante: "Maria Oliveira", setorSolicitante: "Vara Federal 1", siglaServidor: "MOO", matriculaSolicitante: "54321", ramal: "4321", emailContato: "maria.oliveira@trf2.jus.br", dataSolicitacao: new Date("2024-03-05").toISOString(), dataAtendimento: new Date("2024-03-06").toISOString(), documentoIds: ["DOC002"], status: "Atendida" },
  { id: "SOL003", tipo: "Empréstimo", numeroSolicitacao: "SOL-2024-003", nomeSolicitante: "Carlos Pereira", setorSolicitante: "Secretaria", siglaServidor: "CAP", matriculaSolicitante: "67890", ramal: "6789", emailContato: "carlos.pereira@trf2.jus.br", dataSolicitacao: new Date("2024-03-10").toISOString(), dataAtendimento: new Date("2024-03-11").toISOString(), dataDevolucao: new Date("2024-03-20").toISOString(), documentoIds: ["DOC003"], status: "Devolvido" },
];

export type SimulatedDocumentForSolicitacaoDialog = Pick<Documento, 
  'id' | 'numeroDocumento' | 'tipoDocumento' | 'descricaoDocumento' | 'status' | 'codigosCaixa' | 'segredoJustica'
>;

export const allPermissions: { id: keyof Usuario['permissoes']; label: string; description: string }[] = [
  { id: 'dashboard', label: 'Dashboard', description: 'Permite visualizar a tela principal com estatísticas e atalhos.' },
  { id: 'caixas', label: 'Caixas', description: 'Permite gerenciar as caixas de arquivamento.' },
  { id: 'classificacao', label: 'Classificação', description: 'Permite gerenciar os códigos de classificação arquivística.' },
  { id: 'classesJudiciais', label: 'Classes Judiciais', description: 'Permite gerenciar as classes judiciais e seus prazos.' },
  { id: 'acervo', label: 'Acervo', description: 'Permite cadastrar, editar e excluir documentos do acervo.' },
  { id: 'listagens', label: 'Listagens de Eliminação', description: 'Permite criar e gerenciar listagens de eliminação.' },
  { id: 'transferencias', label: 'Transferências', description: 'Permite gerenciar a transferência de documentos para o arquivo.' },
  { id: 'solicitacoes', label: 'Solicitações', description: 'Permite gerenciar solicitações de empréstimo e desarquivamento.' },
  { id: 'buscaAvancada', label: 'Busca Avançada', description: 'Permite utilizar a busca com múltiplos filtros.' },
  { id: 'estatisticas', label: 'Estatísticas', description: 'Permite visualizar gráficos e estatísticas sobre o acervo.' },
  { id: 'relatorios', label: 'Relatórios', description: 'Permite visualizar relatórios tabulares detalhados.' },
  { id: 'auditoria', label: 'Auditoria', description: 'Permite visualizar os logs de auditoria do sistema.' },
  { id: 'usuarios', label: 'Usuários', description: 'Permite gerenciar usuários e suas permissões (somente para administradores).' },
  { id: 'configuracoes', label: 'Configurações', description: 'Permite acessar e alterar as configurações globais do sistema.' },
  { id: 'manual', label: 'Manual', description: 'Permite acessar o manual do sistema.' },
  { id: 'exclusaoDados', label: 'Exclusão de Dados', description: 'Permite excluir registros do sistema (caixas, documentos, etc.). Apenas administradores podem conceder esta permissão.' },
];

export const allTruePermissions: Usuario['permissoes'] = {
  dashboard: true, acervo: true, caixas: true, classificacao: true, classesJudiciais: true, listagens: true, solicitacoes: true, buscaAvancada: true, usuarios: true, configuracoes: true, transferencias: true, estatisticas: true, relatorios: true, auditoria: true, manual: true, exclusaoDados: true,
};

export const standardUserPermissions: Usuario['permissoes'] = {
  ...allTruePermissions,
  usuarios: false,
  configuracoes: false,
  auditoria: false,
  exclusaoDados: false,
};


export const initialUsers: Usuario[] = [
  { id: "USR001", nomeCompleto: "Administrador do Sistema", email: "admin@sistem.com", senhaHash: "hashed_password_1", sigla: "ADM", setor: "TI", statusAprovacao: "Aprovado", tipoUsuario: "Administrador", permissoes: allTruePermissions },
  { id: "USR002", nomeCompleto: "Usuário Padrão", email: "user@sistem.com", senhaHash: "hashed_password_2", sigla: "USER", setor: "Arquivo", statusAprovacao: "Aprovado", tipoUsuario: "Padrão", permissoes: standardUserPermissions },
  { id: "USR003", nomeCompleto: "Usuário Pendente", email: "pending@sistem.com", senhaHash: "hashed_password_3", sigla: "PEND", setor: "Estágio", statusAprovacao: "Pendente", tipoUsuario: "Padrão", permissoes: {} as Usuario['permissoes'] },
  { id: "USR004", nomeCompleto: "Usuário 'r'", email: "r", senhaHash: "hashed_password_4", sigla: "R", setor: "Gabinete X", statusAprovacao: "Aprovado", tipoUsuario: "Padrão", permissoes: { ...standardUserPermissions, dashboard: false, acervo: false, caixas: false, classificacao: false, classesJudiciais: false, listagens: false, buscaAvancada: false, transferencias: false } },
];


export const initialTransferencias: Transferencia[] = [
    {
        id: 'TRANSF_1717088400000',
        nomeServidor: 'Carlos Andrade',
        matricula: '11223',
        ramal: '4567',
        setorRemetente: 'Gabinete do Desembargador X',
        dataTransferencia: new Date('2024-05-30T10:00:00Z').toISOString(),
        status: 'Pendente',
        observacoes: "Transferência urgente de processos concluídos.",
        documentos: [
            {
                id: 'DOC_T_1717088400000_0',
                categoria: 'Processo Judicial',
                codigoClassificacao: '020.1',
                descricao: 'Processo sobre licitação de TI',
                dataAbrangente: '01/2022 - 12/2023',
                numeroDocumento: 'PJ-2022-00123',
                quantidadeVolumes: 2,
                quantidadeApensos: 1,
                numerosApensos: 'AP-2022-001',
                digitalizado: 'Não',
                observacoesGerais: 'Documentação sigilosa.'
            }
        ]
    },
    {
        id: 'TRANSF_1717088500000',
        nomeServidor: 'Lúcia Martins',
        matricula: '44556',
        ramal: '8901',
        setorRemetente: 'Secretaria de Recursos Humanos',
        dataTransferencia: new Date('2024-05-28T15:30:00Z').toISOString(),
        status: 'Aprovada',
        observacoes: "Documentos para arquivo permanente.",
        documentos: [
            {
                id: 'DOC_T_1717088500000_0',
                categoria: 'Dossiê',
                codigoClassificacao: '030.5',
                descricao: 'Dossiê de aposentadoria do servidor Y',
                dataAbrangente: '1990 - 2024',
                numeroDocumento: 'D-S-Y-1990',
                quantidadeVolumes: 1,
                quantidadeApensos: 0,
                numerosApensos: '',
                digitalizado: 'Sim',
                observacoesGerais: ''
            },
            {
                id: 'DOC_T_1717088500000_1',
                categoria: 'Processo Administrativo',
                codigoClassificacao: '045.2',
                descricao: 'Processo de férias de 2023',
                dataAbrangente: '2023',
                numeroDocumento: 'PA-FERIAS-2023',
                quantidadeVolumes: 1,
                quantidadeApensos: 0,
                numerosApensos: '',
                digitalizado: 'Sim',
                observacoesGerais: 'Todos os processos de férias do ano.'
            }
        ]
    }
];

export const initialTiposDocumento: string[] = [
  "Ação Ordinária", 
  "Comunicação Interna", 
  "Execução Fiscal", 
  "Petição", 
  "Procedimento do Juizado Especial Cível", 
  "Requerimento", 
  "Solicitação de Informações"
];

export const initialGenerosDocumentais: string[] = ['Textual', 'Iconográfico', 'Cartográfico', 'Sonoro', 'Filmográfico', 'Audiovisual'];

export const initialTiposMidia: string[] = ['CD-R', 'CD-RW', 'Disquete', 'Pen Drive', 'HD', 'Outro'];

export const initialTiposParte: string[] = ["Autor", "Réu", "Magistrado", "Advogado", "Procurador", "Acusado", "Acusador", "Agravado", "Agravante", "Apelado", "Apelante", "Assistente do Réu", "Coator", "Curador", "Declarante", "Depositante", "Depositário", "Depositário Público", "Deprecado", "Deprecante", "Depreciado", "Embargado", "Embargante", "Espólio", "Executado", "Executante", "Exequado", "Exequente", "Falecido", "Impetrado", "Impetrante", "Impugnado", "Impugnante", "Indiciado", "Inventariado", "Inventariante", "Justificante", "Liquidado", "Liquidante", "Litisconsorte", "Notificado", "Notificante", "Paciente", "Requerente", "Requerido", "Requisitado", "Responsável", "Rogado", "Rogante", "Suplicado", "Suplicante", "Testemunhante", "Vítima"];

export const initialTiposOrigem: TipoOrigem[] = [
  { id: 'to1', nome: 'Tribunal de Justiça', sigla: 'TJ' },
  { id: 'to2', nome: 'Secretaria Municipal', sigla: 'SM' },
  { id: 'to3', nome: 'Câmara de Vereadores', sigla: 'CV' },
  { id: 'to4', nome: 'Advocacia Geral', sigla: 'AG' },
  { id: 'to5', nome: 'Vara Federal', sigla: 'VF' },
  { id: 'to6', nome: 'Juizado Especial', sigla: 'JE' },
  { id: 'to7', nome: 'Secretaria de Recursos Humanos', sigla: 'SRH' },
  { id: 'to8', nome: 'Gabinete do Desembargador X', sigla: 'GAB-DES-X' },
  { id: 'to9', nome: 'Vara Cível', sigla: 'VC' },
];

export const initialTiposCaixa: string[] = [
  "JUD",
  "DOC",
  "ADM",
  "ADM/SIGA",
  "JUD/APOLO",
  "JUD/HÍBRIDO",
  "Pasta"
];

export const initialClassificacoes: Classificacao[] = [
  { id: "CLA001", tipoPlanoClassificacao: "Judicial", codigo: "020.1", descricao: "Processos Judiciais Cíveis", tipoPrazoFaseCorrente: "Anos", prazoGuardaFaseCorrenteAnos: 5, prazoGuardaFaseCorrenteCondicaoTextual: undefined, prazoGuardaFaseIntermediariaAnos: 15, destinacaoFinal: "Guarda Permanente", observacoes: "Manter cópia digitalizada", status: "Ativo" },
  { id: "CLA002", tipoPlanoClassificacao: "Administrativo", codigo: "030.5", descricao: "Correspondências Recebidas", tipoPrazoFaseCorrente: "Condição Textual", prazoGuardaFaseCorrenteAnos: undefined, prazoGuardaFaseCorrenteCondicaoTextual: "Até a próxima atualização", prazoGuardaFaseIntermediariaAnos: 3, destinacaoFinal: "Eliminação", observacoes: "", status: "Inativo" },
  { id: "CLA003", tipoPlanoClassificacao: "Administrativo", codigo: "045.2", descricao: "Relatórios Anuais", tipoPrazoFaseCorrente: "Anos", prazoGuardaFaseCorrenteAnos: 1, prazoGuardaFaseCorrenteCondicaoTextual: undefined, prazoGuardaFaseIntermediariaAnos: 0, destinacaoFinal: "Guarda Permanente", observacoes: "Manter permanentemente na fase intermediária", status: "Ativo" },
  { id: "CLA004", tipoPlanoClassificacao: "Administrativo", codigo: "020.1", descricao: "Contratos Administrativos", tipoPrazoFaseCorrente: "Anos", prazoGuardaFaseCorrenteAnos: 5, prazoGuardaFaseIntermediariaAnos: 10, destinacaoFinal: "Eliminação", observacoes: "Exemplo de código duplicado em plano diferente.", status: "Ativo" },
];

export const initialClassesJudiciais: ClasseJudicial[] = [
  { id: "CJ001", codigo: "1116", descricao: "Procedimento Comum Cível", prazoGuardaAnos: 2, destinacaoFinal: "Eliminação", inativo: false, observacoes: "Revisar após decisão do CNJ." },
  { id: "CJ002", codigo: "22", descricao: "Ação Penal - Procedimento Ordinário", prazoGuardaAnos: 5, destinacaoFinal: "Guarda Permanente", inativo: false },
  { id: "CJ003", codigo: "12078", descricao: "Cumprimento de Sentença", prazoGuardaAnos: 0, destinacaoFinal: "Vide Guia de Aplicação", inativo: true, observacoes: "Arquivar processo principal junto." },
  { id: "CJ004", codigo: "99", descricao: "Carta Precatória Cível", destinacaoFinal: "Não se Aplica", inativo: false },
];

export const PARTES_STORAGE_KEY = 'arquivocentral_partes';

export const initialPartes: ParteDetalhe[] = [
  { id: 'P001', nome: 'Empresa Exemplo Ltda', cpfCnpj: '12.345.678/0001-99', iniciais: 'EEL' },
  { id: 'P002', nome: 'Maria Santos', cpfCnpj: '123.456.789-00', iniciais: 'MS' },
  { id: 'P003', nome: 'João da Silva', iniciais: 'JS' },
  { id: 'P004', nome: 'Fazenda Nacional', cpfCnpj: '00.394.460/0001-41', iniciais: 'FN' },
];





